name: Python package release
on:
  release:
    types: [created]
jobs:
  release:
    # specify the instance
    runs-on: ubuntu-latest
    steps:
    # checkout the repository to master
    # and use it as the current working directory
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        # release and testing dependencies
        pip install twine flake8
    - name: Lint with flake8instance
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Python package
      run: |
        python setup.py sdist bdist_wheel
    
    - name: Twine check
      run: |
        twine check dist/*
        
    - name: Publish to PyPI
      run: |
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}
